import ui.eventdispatcher

#CONSTANTS:
UIEVENT = 25

#Event IDs:
KEYDOWNEVENT = 2
MOUSEMOTIONEVENT = 4
MOUSEBUTTONDOWNEVENT = 5
MOUSEBUTTONUPEVENT = 6
BUTTONPRESSEVENT = 25.0001
CARETTIMEREVENT = 25.0002
